version: '3.1'
services:
  db:
    image: mysql
    container_name: TDS_API
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - db-volume:/var/lib/mysql
volumes:
  db-volume: